package com.cmit.clouddetection.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cmit.clouddetection.entry.Script;
import com.cmit.clouddetection.entry.ScriptDetails;

import com.cmit.clouddetection.dao.ScriptDao;
import com.cmit.clouddetection.dao.ScriptDetailsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scriptDaoConfig;
    private final DaoConfig scriptDetailsDaoConfig;

    private final ScriptDao scriptDao;
    private final ScriptDetailsDao scriptDetailsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scriptDaoConfig = daoConfigMap.get(ScriptDao.class).clone();
        scriptDaoConfig.initIdentityScope(type);

        scriptDetailsDaoConfig = daoConfigMap.get(ScriptDetailsDao.class).clone();
        scriptDetailsDaoConfig.initIdentityScope(type);

        scriptDao = new ScriptDao(scriptDaoConfig, this);
        scriptDetailsDao = new ScriptDetailsDao(scriptDetailsDaoConfig, this);

        registerDao(Script.class, scriptDao);
        registerDao(ScriptDetails.class, scriptDetailsDao);
    }
    
    public void clear() {
        scriptDaoConfig.clearIdentityScope();
        scriptDetailsDaoConfig.clearIdentityScope();
    }

    public ScriptDao getScriptDao() {
        return scriptDao;
    }

    public ScriptDetailsDao getScriptDetailsDao() {
        return scriptDetailsDao;
    }

}
