package com.cmit.clouddetection.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cmit.clouddetection.entry.Script;
import com.cmit.clouddetection.entry.ScriptDetails;
import com.cmit.clouddetection.entry.TaskResult;
import com.cmit.clouddetection.entry.TaskResultDetail;

import com.cmit.clouddetection.dao.ScriptDao;
import com.cmit.clouddetection.dao.ScriptDetailsDao;
import com.cmit.clouddetection.dao.TaskResultDao;
import com.cmit.clouddetection.dao.TaskResultDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scriptDaoConfig;
    private final DaoConfig scriptDetailsDaoConfig;
    private final DaoConfig taskResultDaoConfig;
    private final DaoConfig taskResultDetailDaoConfig;

    private final ScriptDao scriptDao;
    private final ScriptDetailsDao scriptDetailsDao;
    private final TaskResultDao taskResultDao;
    private final TaskResultDetailDao taskResultDetailDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scriptDaoConfig = daoConfigMap.get(ScriptDao.class).clone();
        scriptDaoConfig.initIdentityScope(type);

        scriptDetailsDaoConfig = daoConfigMap.get(ScriptDetailsDao.class).clone();
        scriptDetailsDaoConfig.initIdentityScope(type);

        taskResultDaoConfig = daoConfigMap.get(TaskResultDao.class).clone();
        taskResultDaoConfig.initIdentityScope(type);

        taskResultDetailDaoConfig = daoConfigMap.get(TaskResultDetailDao.class).clone();
        taskResultDetailDaoConfig.initIdentityScope(type);

        scriptDao = new ScriptDao(scriptDaoConfig, this);
        scriptDetailsDao = new ScriptDetailsDao(scriptDetailsDaoConfig, this);
        taskResultDao = new TaskResultDao(taskResultDaoConfig, this);
        taskResultDetailDao = new TaskResultDetailDao(taskResultDetailDaoConfig, this);

        registerDao(Script.class, scriptDao);
        registerDao(ScriptDetails.class, scriptDetailsDao);
        registerDao(TaskResult.class, taskResultDao);
        registerDao(TaskResultDetail.class, taskResultDetailDao);
    }
    
    public void clear() {
        scriptDaoConfig.clearIdentityScope();
        scriptDetailsDaoConfig.clearIdentityScope();
        taskResultDaoConfig.clearIdentityScope();
        taskResultDetailDaoConfig.clearIdentityScope();
    }

    public ScriptDao getScriptDao() {
        return scriptDao;
    }

    public ScriptDetailsDao getScriptDetailsDao() {
        return scriptDetailsDao;
    }

    public TaskResultDao getTaskResultDao() {
        return taskResultDao;
    }

    public TaskResultDetailDao getTaskResultDetailDao() {
        return taskResultDetailDao;
    }

}
