package com.cmit.clouddetection.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.cmit.clouddetection.entry.ScriptDetails;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCRIPT_DETAILS".
*/
public class ScriptDetailsDao extends AbstractDao<ScriptDetails, Void> {

    public static final String TABLENAME = "SCRIPT_DETAILS";

    /**
     * Properties of entity ScriptDetails.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property StepId = new Property(0, String.class, "stepId", false, "STEP_ID");
        public final static Property SerialNum = new Property(1, String.class, "serialNum", false, "SERIAL_NUM");
        public final static Property OperateType = new Property(2, String.class, "operateType", false, "OPERATE_TYPE");
        public final static Property ParamValue = new Property(3, String.class, "paramValue", false, "PARAM_VALUE");
        public final static Property SuccessKeyword = new Property(4, String.class, "successKeyword", false, "SUCCESS_KEYWORD");
        public final static Property IsTimeStamp = new Property(5, int.class, "isTimeStamp", false, "IS_TIME_STAMP");
    }


    public ScriptDetailsDao(DaoConfig config) {
        super(config);
    }
    
    public ScriptDetailsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCRIPT_DETAILS\" (" + //
                "\"STEP_ID\" TEXT," + // 0: stepId
                "\"SERIAL_NUM\" TEXT," + // 1: serialNum
                "\"OPERATE_TYPE\" TEXT," + // 2: operateType
                "\"PARAM_VALUE\" TEXT," + // 3: paramValue
                "\"SUCCESS_KEYWORD\" TEXT," + // 4: successKeyword
                "\"IS_TIME_STAMP\" INTEGER NOT NULL );"); // 5: isTimeStamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCRIPT_DETAILS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ScriptDetails entity) {
        stmt.clearBindings();
 
        String stepId = entity.getStepId();
        if (stepId != null) {
            stmt.bindString(1, stepId);
        }
 
        String serialNum = entity.getSerialNum();
        if (serialNum != null) {
            stmt.bindString(2, serialNum);
        }
 
        String operateType = entity.getOperateType();
        if (operateType != null) {
            stmt.bindString(3, operateType);
        }
 
        String paramValue = entity.getParamValue();
        if (paramValue != null) {
            stmt.bindString(4, paramValue);
        }
 
        String successKeyword = entity.getSuccessKeyword();
        if (successKeyword != null) {
            stmt.bindString(5, successKeyword);
        }
        stmt.bindLong(6, entity.getIsTimeStamp());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ScriptDetails entity) {
        stmt.clearBindings();
 
        String stepId = entity.getStepId();
        if (stepId != null) {
            stmt.bindString(1, stepId);
        }
 
        String serialNum = entity.getSerialNum();
        if (serialNum != null) {
            stmt.bindString(2, serialNum);
        }
 
        String operateType = entity.getOperateType();
        if (operateType != null) {
            stmt.bindString(3, operateType);
        }
 
        String paramValue = entity.getParamValue();
        if (paramValue != null) {
            stmt.bindString(4, paramValue);
        }
 
        String successKeyword = entity.getSuccessKeyword();
        if (successKeyword != null) {
            stmt.bindString(5, successKeyword);
        }
        stmt.bindLong(6, entity.getIsTimeStamp());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ScriptDetails readEntity(Cursor cursor, int offset) {
        ScriptDetails entity = new ScriptDetails( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // stepId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // serialNum
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // operateType
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // paramValue
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // successKeyword
            cursor.getInt(offset + 5) // isTimeStamp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ScriptDetails entity, int offset) {
        entity.setStepId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSerialNum(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOperateType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setParamValue(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSuccessKeyword(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIsTimeStamp(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ScriptDetails entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ScriptDetails entity) {
        return null;
    }

    @Override
    public boolean hasKey(ScriptDetails entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
