package com.cmit.clouddetection.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.cmit.clouddetection.entry.Script;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCRIPT".
*/
public class ScriptDao extends AbstractDao<Script, Long> {

    public static final String TABLENAME = "SCRIPT";

    /**
     * Properties of entity Script.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ScriptId = new Property(1, int.class, "scriptId", false, "SCRIPT_ID");
        public final static Property TaskId = new Property(2, int.class, "taskId", false, "TASK_ID");
        public final static Property StrategyId = new Property(3, int.class, "strategyId", false, "STRATEGY_ID");
        public final static Property Operator = new Property(4, int.class, "operator", false, "OPERATOR");
        public final static Property Province = new Property(5, String.class, "province", false, "PROVINCE");
        public final static Property BusinessName = new Property(6, String.class, "businessName", false, "BUSINESS_NAME");
        public final static Property Aided = new Property(7, int.class, "aided", false, "AIDED");
        public final static Property InstanceName = new Property(8, String.class, "instanceName", false, "INSTANCE_NAME");
        public final static Property PhoneNum = new Property(9, String.class, "phoneNum", false, "PHONE_NUM");
        public final static Property TaskSerial = new Property(10, Long.class, "taskSerial", false, "TASK_SERIAL");
    }


    public ScriptDao(DaoConfig config) {
        super(config);
    }
    
    public ScriptDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCRIPT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SCRIPT_ID\" INTEGER NOT NULL ," + // 1: scriptId
                "\"TASK_ID\" INTEGER NOT NULL ," + // 2: taskId
                "\"STRATEGY_ID\" INTEGER NOT NULL ," + // 3: strategyId
                "\"OPERATOR\" INTEGER NOT NULL ," + // 4: operator
                "\"PROVINCE\" TEXT," + // 5: province
                "\"BUSINESS_NAME\" TEXT," + // 6: businessName
                "\"AIDED\" INTEGER NOT NULL ," + // 7: aided
                "\"INSTANCE_NAME\" TEXT," + // 8: instanceName
                "\"PHONE_NUM\" TEXT," + // 9: phoneNum
                "\"TASK_SERIAL\" INTEGER);"); // 10: taskSerial
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCRIPT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Script entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getScriptId());
        stmt.bindLong(3, entity.getTaskId());
        stmt.bindLong(4, entity.getStrategyId());
        stmt.bindLong(5, entity.getOperator());
 
        String province = entity.getProvince();
        if (province != null) {
            stmt.bindString(6, province);
        }
 
        String businessName = entity.getBusinessName();
        if (businessName != null) {
            stmt.bindString(7, businessName);
        }
        stmt.bindLong(8, entity.getAided());
 
        String instanceName = entity.getInstanceName();
        if (instanceName != null) {
            stmt.bindString(9, instanceName);
        }
 
        String phoneNum = entity.getPhoneNum();
        if (phoneNum != null) {
            stmt.bindString(10, phoneNum);
        }
 
        Long taskSerial = entity.getTaskSerial();
        if (taskSerial != null) {
            stmt.bindLong(11, taskSerial);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Script entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getScriptId());
        stmt.bindLong(3, entity.getTaskId());
        stmt.bindLong(4, entity.getStrategyId());
        stmt.bindLong(5, entity.getOperator());
 
        String province = entity.getProvince();
        if (province != null) {
            stmt.bindString(6, province);
        }
 
        String businessName = entity.getBusinessName();
        if (businessName != null) {
            stmt.bindString(7, businessName);
        }
        stmt.bindLong(8, entity.getAided());
 
        String instanceName = entity.getInstanceName();
        if (instanceName != null) {
            stmt.bindString(9, instanceName);
        }
 
        String phoneNum = entity.getPhoneNum();
        if (phoneNum != null) {
            stmt.bindString(10, phoneNum);
        }
 
        Long taskSerial = entity.getTaskSerial();
        if (taskSerial != null) {
            stmt.bindLong(11, taskSerial);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Script readEntity(Cursor cursor, int offset) {
        Script entity = new Script( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // scriptId
            cursor.getInt(offset + 2), // taskId
            cursor.getInt(offset + 3), // strategyId
            cursor.getInt(offset + 4), // operator
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // province
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // businessName
            cursor.getInt(offset + 7), // aided
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // instanceName
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // phoneNum
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10) // taskSerial
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Script entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setScriptId(cursor.getInt(offset + 1));
        entity.setTaskId(cursor.getInt(offset + 2));
        entity.setStrategyId(cursor.getInt(offset + 3));
        entity.setOperator(cursor.getInt(offset + 4));
        entity.setProvince(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBusinessName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAided(cursor.getInt(offset + 7));
        entity.setInstanceName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setPhoneNum(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTaskSerial(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Script entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Script entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Script entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
