package com.cmit.clouddetection.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.cmit.clouddetection.entry.TaskResultDetail;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TASK_RESULT_DETAIL".
*/
public class TaskResultDetailDao extends AbstractDao<TaskResultDetail, String> {

    public static final String TABLENAME = "TASK_RESULT_DETAIL";

    /**
     * Properties of entity TaskResultDetail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ScriptId = new Property(0, String.class, "scriptId", true, "ID");
        public final static Property SerialNum = new Property(1, String.class, "serialNum", false, "SERIAL_NUM");
        public final static Property OperateNum = new Property(2, String.class, "operateNum", false, "OPERATE_NUM");
        public final static Property ParamValue = new Property(3, String.class, "paramValue", false, "PARAM_VALUE");
        public final static Property SuccessKeyword = new Property(4, String.class, "successKeyword", false, "SUCCESS_KEYWORD");
        public final static Property IsTimeStamp = new Property(5, String.class, "isTimeStamp", false, "IS_TIME_STAMP");
        public final static Property RunningResult = new Property(6, String.class, "runningResult", false, "RUNNING_RESULT");
        public final static Property SingleStepBeginTime = new Property(7, String.class, "singleStepBeginTime", false, "SINGLE_STEP_BEGIN_TIME");
        public final static Property SingleStepEndTime = new Property(8, String.class, "singleStepEndTime", false, "SINGLE_STEP_END_TIME");
        public final static Property ResultScreenShot = new Property(9, String.class, "resultScreenShot", false, "RESULT_SCREEN_SHOT");
    }


    public TaskResultDetailDao(DaoConfig config) {
        super(config);
    }
    
    public TaskResultDetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASK_RESULT_DETAIL\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: scriptId
                "\"SERIAL_NUM\" TEXT," + // 1: serialNum
                "\"OPERATE_NUM\" TEXT," + // 2: operateNum
                "\"PARAM_VALUE\" TEXT," + // 3: paramValue
                "\"SUCCESS_KEYWORD\" TEXT," + // 4: successKeyword
                "\"IS_TIME_STAMP\" TEXT," + // 5: isTimeStamp
                "\"RUNNING_RESULT\" TEXT," + // 6: runningResult
                "\"SINGLE_STEP_BEGIN_TIME\" TEXT," + // 7: singleStepBeginTime
                "\"SINGLE_STEP_END_TIME\" TEXT," + // 8: singleStepEndTime
                "\"RESULT_SCREEN_SHOT\" TEXT);"); // 9: resultScreenShot
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK_RESULT_DETAIL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TaskResultDetail entity) {
        stmt.clearBindings();
 
        String scriptId = entity.getScriptId();
        if (scriptId != null) {
            stmt.bindString(1, scriptId);
        }
 
        String serialNum = entity.getSerialNum();
        if (serialNum != null) {
            stmt.bindString(2, serialNum);
        }
 
        String operateNum = entity.getOperateNum();
        if (operateNum != null) {
            stmt.bindString(3, operateNum);
        }
 
        String paramValue = entity.getParamValue();
        if (paramValue != null) {
            stmt.bindString(4, paramValue);
        }
 
        String successKeyword = entity.getSuccessKeyword();
        if (successKeyword != null) {
            stmt.bindString(5, successKeyword);
        }
 
        String isTimeStamp = entity.getIsTimeStamp();
        if (isTimeStamp != null) {
            stmt.bindString(6, isTimeStamp);
        }
 
        String runningResult = entity.getRunningResult();
        if (runningResult != null) {
            stmt.bindString(7, runningResult);
        }
 
        String singleStepBeginTime = entity.getSingleStepBeginTime();
        if (singleStepBeginTime != null) {
            stmt.bindString(8, singleStepBeginTime);
        }
 
        String singleStepEndTime = entity.getSingleStepEndTime();
        if (singleStepEndTime != null) {
            stmt.bindString(9, singleStepEndTime);
        }
 
        String resultScreenShot = entity.getResultScreenShot();
        if (resultScreenShot != null) {
            stmt.bindString(10, resultScreenShot);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TaskResultDetail entity) {
        stmt.clearBindings();
 
        String scriptId = entity.getScriptId();
        if (scriptId != null) {
            stmt.bindString(1, scriptId);
        }
 
        String serialNum = entity.getSerialNum();
        if (serialNum != null) {
            stmt.bindString(2, serialNum);
        }
 
        String operateNum = entity.getOperateNum();
        if (operateNum != null) {
            stmt.bindString(3, operateNum);
        }
 
        String paramValue = entity.getParamValue();
        if (paramValue != null) {
            stmt.bindString(4, paramValue);
        }
 
        String successKeyword = entity.getSuccessKeyword();
        if (successKeyword != null) {
            stmt.bindString(5, successKeyword);
        }
 
        String isTimeStamp = entity.getIsTimeStamp();
        if (isTimeStamp != null) {
            stmt.bindString(6, isTimeStamp);
        }
 
        String runningResult = entity.getRunningResult();
        if (runningResult != null) {
            stmt.bindString(7, runningResult);
        }
 
        String singleStepBeginTime = entity.getSingleStepBeginTime();
        if (singleStepBeginTime != null) {
            stmt.bindString(8, singleStepBeginTime);
        }
 
        String singleStepEndTime = entity.getSingleStepEndTime();
        if (singleStepEndTime != null) {
            stmt.bindString(9, singleStepEndTime);
        }
 
        String resultScreenShot = entity.getResultScreenShot();
        if (resultScreenShot != null) {
            stmt.bindString(10, resultScreenShot);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public TaskResultDetail readEntity(Cursor cursor, int offset) {
        TaskResultDetail entity = new TaskResultDetail( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // scriptId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // serialNum
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // operateNum
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // paramValue
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // successKeyword
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // isTimeStamp
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // runningResult
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // singleStepBeginTime
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // singleStepEndTime
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // resultScreenShot
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TaskResultDetail entity, int offset) {
        entity.setScriptId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSerialNum(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOperateNum(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setParamValue(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSuccessKeyword(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIsTimeStamp(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRunningResult(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSingleStepBeginTime(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSingleStepEndTime(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setResultScreenShot(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final String updateKeyAfterInsert(TaskResultDetail entity, long rowId) {
        return entity.getScriptId();
    }
    
    @Override
    public String getKey(TaskResultDetail entity) {
        if(entity != null) {
            return entity.getScriptId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TaskResultDetail entity) {
        return entity.getScriptId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
